services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xccm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181"] # Simple check command
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - xccm-network
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      # L'application interne (app) utilise le service 'kafka' (port 9092 interne)
      - "9092:9092"
      # Le listener OUTSIDE utilise le port 9093 interne, mais est mappé au port 9092 de l'hôte
      - "9094:9093" # NOUVEAU MAPPAGE
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      # PLAINTEXT est interne à Docker, utilise le port 9092 interne du conteneur.
      # OUTSIDE est pour l'externe (localhost), il utilise le port 9093 interne du conteneur.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094 
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      
      # On change le port du listener OUTSIDE à 9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093 
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9093 || exit 1"] # Le healthcheck doit maintenant tester le port OUTSIDE (9093)
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - xccm-network

  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_URL: jdbc:postgresql://${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy 
    networks:
      - xccm-network

volumes:
  postgres_data:

networks:
  xccm-network:
    driver: bridge
